version: "3.9"
services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: fedena_db
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fedena_app
    command: bash -c "rm -f tmp/pids/server.pid && script/server -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

volumes:
  gem_cache:
  mariadb_data: